### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###
POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
  "name": "Somia",
  "email": "Somia2@gmail.com",
  "password": "123456",
  "role": "expert",
  "yearsExperience": 8
}

###

POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
  "name": "Sadeem",
  "email": "Sadeem@gmail.com",
  "password": "123456",
  "role": "gardener"
}

###

POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
  "name": "Anwar",
  "email": "Anwar@gmail.com",
  "password": "123456",
  "role": "store"
}

###

POST http://localhost:5050/api/auth/register
Content-Type: application/json

{

  "name": "Raghada",
  "email": "Raghada@gmail.com",
  "password": "123456",
  "role": "admin"
}


### LOGIN
POST http://localhost:5050/api/auth/login
Content-Type: application/json

{
  "email": "Raghada@gmail.com",
  "password": "123456"
}

###
POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
  "name": "Dr. Lina Alharbi",
  "email": "linaNEW@gmail.com",
  "password": "123456",
  "role": "expert",
  "yearsExperience": 10,
  "bio": "Expert in plants",
  "certificates": ["Cert 1"],
  "expertStatus": "Pending"
}

###
POST http://localhost:5050/api/question
Content-Type: application/json

{
  "title": "Inappropriate language in plant discussion",
  "content": "This post was reported because it contains inappropriate language.",
  "author": "User123",
  "reports": 5,
  "status": "Active"
}

###
GET http://localhost:5050/api/reviews

###

POST http://localhost:5050/api/question
Content-Type: application/json

{
  "title": "Spam link in comment section",
  "content": "This post was reported because it includes spam links.",
  "author": "SpamBot99",
  "reports": 12,
  "status": "Active"
}






